# Build stage
FROM node:20-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Production stage
FROM nginx:stable-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Copy the build output to nginx html folder
COPY --from=build /app/dist /usr/share/nginx/html
# Copy a custom nginx config to handle SPA routing if necessary
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]